"""add user_uid to books

Revision ID: 4bfa5200d64b
Revises: f48fcb12caf4
Create Date: 2026-06-23 23:13:24.277054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4bfa5200d64b'
down_revision: Union[str, Sequence[str], None] = 'f48fcb12caf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('books_user_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_user_id_fkey'), 'books', 'users', ['user_id'], ['uid'])
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
